-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tb_groups
(
    group_id integer NOT NULL DEFAULT nextval('tb_groups_group_id_seq'::regclass),
    group_name character varying COLLATE pg_catalog."default",
    CONSTRAINT tb_groups_pkey PRIMARY KEY (group_id)
);

CREATE TABLE IF NOT EXISTS public.tb_links
(
    link_id integer NOT NULL DEFAULT nextval('tb_links_link_id_seq'::regclass),
    user_id integer,
    group_id integer,
    link_title character varying(30) COLLATE pg_catalog."default",
    shorted_url character varying COLLATE pg_catalog."default",
    origin_url character varying COLLATE pg_catalog."default",
    created_at date,
    updated_at timestamp without time zone,
    CONSTRAINT tb_links_pkey PRIMARY KEY (link_id),
    CONSTRAINT tb_links_shorted_url_key UNIQUE (shorted_url)
);

CREATE TABLE IF NOT EXISTS public.tb_users
(
    user_id integer NOT NULL DEFAULT nextval('tb_users_user_id_seq'::regclass),
    first_name character varying(20) COLLATE pg_catalog."default",
    last_name character varying(20) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    email_address character varying(30) COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    registered_at date,
    CONSTRAINT tb_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT tb_users_email_address_key UNIQUE (email_address),
    CONSTRAINT tb_users_pub_id_key UNIQUE (pub_id)
);

ALTER TABLE IF EXISTS public.tb_links
    ADD CONSTRAINT group_fk FOREIGN KEY (group_id)
    REFERENCES public.tb_groups (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tb_links
    ADD CONSTRAINT user_fk FOREIGN KEY (user_id)
    REFERENCES public.tb_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;